universibo_shibboleth_login:
  pattern: /login
  defaults: { _controller: 'UniversiboShibbolethBundle:Security:login' }
universibo_shibboleth_logout:
  pattern: /logout
  defaults: { _controller: 'UniversiboShibbolethBundle:Security:logout' }
universibo_shibboleth_prelogout:
  pattern: /prelogout
  defaults: { _controller: 'UniversiboShibbolethBundle:Security:prelogout' }
universibo_shibboleth_shiblogout:
  pattern: /shiblogout
  defaults: { _controller: 'UniversiboShibbolethBundle:Security:shiblogout' }
