services:
  universibo_shibboleth.security.authentication.provider:
    class: 'Universibo\Bundle\ShibbolethBundle\Security\Authentication\Provider\ShibbolethProvider'
    arguments: ['']
  universibo_shibboleth.security.authentication.listener:
    class: 'Universibo\Bundle\ShibbolethBundle\Security\Firewall\ShibbolethListener'
    arguments: ['@security.context','@security.authentication.manager','%universibo_shibboleth.claims%']
