services:
  universibo_shibboleth.cookie.cleaner:
    class: 'Universibo\Bundle\ShibbolethBundle\Http\Cookie\CookieCleaner'
  universibo_shibboleth.controller.security:
    class: 'Universibo\Bundle\ShibbolethBundle\Controller\SecurityController'
    arguments:
      - '@http_kernel'
      - '@security.context'
      - '@router'
      - '@universibo_shibboleth.logout_handler'
      - '%universibo_shibboleth.firewall_name%'
      - '%universibo_shibboleth.route.after_login%'
      - '%universibo_shibboleth.idp_url.logout%'
  universibo_shibboleth.security.authentication.provider:
    class: 'Universibo\Bundle\ShibbolethBundle\Security\Authentication\Provider\ShibbolethProvider'
    arguments: ['@universibo_shibboleth.user_provider']
  universibo_shibboleth.security.authentication.listener:
    class: 'Universibo\Bundle\ShibbolethBundle\Security\Firewall\ShibbolethListener'
    arguments:
      - '@security.context'
      - '@security.authentication.manager'
      - '@event_dispatcher'
      - '@logger'
      - '%universibo_shibboleth.claims%'
  universibo_shibboleth.logout_handler:
    class: 'Universibo\Bundle\ShibbolethBundle\Security\Http\Logout\ShibbolethLogoutHandler'
    arguments:
      - '@router'
      - '@universibo_shibboleth.cookie.cleaner'
